export const PRESENTATION_ERROR = 'presentation_error'
export const UNKNOWN_ERROR = 'unknown_error'
export const INVALID_JSONLD = 'invalid_jsonld'
export const NO_VC_CONTEXT = 'no_vc_context'
export const INVALID_CREDENTIAL_ID = 'invalid_credential_id'
export const NO_PROOF = 'no_proof'
export const HTTP_ERROR_WITH_SIGNATURE_CHECK = 'http_error_with_signature_check'
export const DID_WEB_UNRESOLVED = 'did_web_unresolved'
export const INVALID_SIGNATURE = 'invalid_signature'

export const STATUS_LIST_NOT_FOUND = 'status_list_not_found'
export const STATUS_LIST_EXPIRED = 'status_list_expired'
export const UNKNOWN_STATUS_LIST_ERROR = 'status_list_error'
export const STATUS_LIST_SIGNATURE_ERROR = 'status_list_signature_error'
export const STATUS_LIST_TYPE_ERROR = 'status_list_type_error'
export const STATUS_LIST_NOT_YET_VALID_ERROR = 'status_list_not_yet_valid'